#pragma once

#include <algorithm>
#include <cmath>
#include <limits>
#include <even/NewtonSolver.h>
#include <even/BjtModel.h>

//==============================================================================
// even::Ba283OutputStage -- the Neve BA283 output amplifier, extracted from
// plugins/neve1073 (where it was developed and validated) so both the preamp
// and the EQ plugin share one model. The console has exactly ONE of these per
// channel (post-EQ makeup/output stage); a plugin chain stacking preamp + EQ
// must therefore not double it (see docs/neve1073eq.md).
//
// Topology (component-level, 4-node MNA + Newton-Raphson):
//
//   Nodes: 0 = driver base, 1 = driver emitter, 2 = driver collector (the
//   bias-spreader drive), 3 = output. The driver is a full Ebers-Moll BJT
//   biased by its own divider (Rb1/Rb2) and degenerated by ReD; the global
//   feedback resistor Rf returns the output to the driver BASE (see the rf
//   note below), so driver gain compression progressively fills in the
//   pair's crossover notch as drive increases -- the characteristic BA283
//   behaviour a bare 2-node pair cannot reproduce. The driver collector
//   feeds the spreader (~2*Vbe) and the Class-AB complementary pair
//   (BC184L NPN / BC214L PNP), whose junction currents use a reduced
//   exponential model with per-device emitter degeneration.
//
// The stage input is the preceding stage's collector signal minus its DC
// level: the behavioural equivalent of the interstage coupling, so the
// driver's own divider alone sets the idle point. The output is the AC
// signal on node 3 (caller subtracts the quiescent DC, quiescentVo).
namespace even
{

class Ba283OutputStage
{
public:
    struct PpState { double b, e, c, o; }; // driver b/e/c + output node
    using Vec = even::NewtonSolver<4>::Vec;
    using Mat = even::NewtonSolver<4>::Mat;

    double vcc = 24.0;     // positive rail (driver collector load)
    double rs   = 600.0;   // drive source impedance
    double rb1  = 33.0e3;  // vcc -> driver base
    double rb2  = 12.1e3;  // driver base -> gnd. Divider + reD set the
                           // driver's idle. reD = 2.4k sets the idle
                           // current (~2.5 mA => ve ~ 6.0 V); the divider
                           // Thevenin (~6.44 V) idles the collector
                           // deliberately slightly below the midpoint of
                           // its swing, giving the single-supply stage its
                           // mild hardware-style asymmetry (clip levels
                           // ~ -5.6 / +6.9, ratio ~1.2:1) and the touch
                           // of even-order harmonic that is part of the
                           // 1073 character.
    double vth  = 24.0 * 12.1e3 / (33.0e3 + 12.1e3); // divider Thevenin
    double reD  = 2.4e3;   // driver emitter degeneration
    double rcD  = 3.6e3;   // driver collector load
    double rf   = 4.7e3;   // global feedback, output -> driver BASE.
                           // Sign matters: the CE->driver->pair chain is
                           // net inverting (the pair is an emitter
                           // follower), so returning NFB to the driver's
                           // EMITTER makes the loop positive (measured:
                           // relaxation oscillation, 44% THD). Summed into
                           // the base node it is negative, and the loop
                           // gain is self-limiting: highest in the pair's
                           // crossover notch (driver gain ~7, pair gm
                           // collapsed -> |T| ~ 0.5, which is exactly the
                           // notch-filling compression) and ~0.12 where
                           // the pair conducts.
    double nfbRef = 0.0;   // output quiescent DC (set in prepare): the
                           // feedback path is AC-coupled through the
                           // output transformer, so only the AC part of
                           // the output reaches the driver base
    double rl   = 600.0;   // load (output transformer primary reflected)
    double bias = 0.62;    // ~2*Vbe/2 spreader drop per half
    double reP  = 4.7;     // output device emitter degeneration. The
                           // pair's raw exponential (gm ~ 0.85 S at the
                           // ~20 mA idle) is a razor-edged crossover the
                           // driver's gain then amplifies into a buzz;
                           // degeneration flattens the turn-on exactly as
                           // the physical emitter resistors do.
    double IsP  = 2.0e-6;  // power-device scaled saturation current
    double beta = 100.0;   // output device beta
    double Vt   = 0.025852;
    // Driver BJT. The 5th initializer is the reverse-junction current cap
    // (BjtModel::irCap): without it, deep driver saturation lets the
    // base->collector current grow unbounded, dragging the collector (and
    // with it the output) back UP -- the transfer curve fold-back that made
    // the negative half of the waveform reverse (double-dip "W") and engage
    // at a fraction of the positive half's level. Capped, the driver bottoms
    // out and the stage clips flat. The cap sits a little above the stage's
    // max legitimate conduction (vcc/rcD ~ 6.7 mA) so normal saturation
    // still behaves physically; only the pathological deep-saturation
    // region is limited.
    even::BjtModel drv { 3.5e-14, 100.0, 4.0, 0.025852, 8.0e-3 };

    // Warm-start caches for the pair's degenerated junction solves: the
    // last (drive argument, root current, dI/dvArg) per junction. Mutable:
    // updated from inside the otherwise-const evaluate. NaN vArg = cold.
    mutable double jnV = std::numeric_limits<double>::quiet_NaN();
    mutable double jnI = 0.0, jnS = 0.0;
    mutable double jpV = std::numeric_limits<double>::quiet_NaN();
    mutable double jpI = 0.0, jpS = 0.0;

    // Quiescent fallback seed for unconverged solves (physical fallback),
    // and the output node's quiescent DC. Set from prepare() after the DC
    // fixed-point; solve() retries from it if continuation fails.
    Vec quiescentSeed {};
    double quiescentVo = 0.0;

    void coldStart()
    {
        // Cold-start the junction warm-start caches: a stale cache from a
        // previously prepared rate would extrapolate from a far-away
        // operating point on the first samples (harmless -- the solve still
        // converges to the same unique root -- but wasteful).
        jnV = jpV = std::numeric_limits<double>::quiet_NaN();
    }

    // Residual-only evaluation (line search / verification calls).
    static void residual (const Ba283OutputStage& s, double vin,
                          const Vec& x, Vec& F)
    {
        evaluate (s, vin, x, F, nullptr);
    }

    // Residual and Jacobian in one pass: both use the same junction limiting
    // and exponential evaluations. J == nullptr means residual-only.
    static void evaluate (const Ba283OutputStage& s, double vin,
                          const Vec& x, Vec& F, Mat* J)
    {
        const double vb = x[0], ve = x[1], vc = x[2], vo = x[3];

        // Driver: full Ebers-Moll (forward + reverse junction), so its
        // saturation -- the collector bottoming against the emitter under
        // drive -- is modelled properly. That saturation is the stage's
        // gain-compression mechanism.
        const auto op = s.drv.eval (vb - ve, vb - vc);

        // Pair junctions, driven from the driver collector through the
        // spreader offset, each degenerated by its emitter resistor. The
        // degenerated junction current i = IsP*(ex((vLim - i*reP)/Vt) - 1)
        // is a monotone scalar equation (unique root, d/di = 1 + reP*gm > 0);
        // it is solved by a short inner Newton and its analytic slope feeds
        // the outer Jacobian.
        const double uN = vc - vo - s.bias;
        double diN, diP;
        const double iN = juncSolve (s, s.jnV, s.jnI, s.jnS,  uN, diN); // sources output node
        const double iP = juncSolve (s, s.jpV, s.jpI, s.jpS, -uN, diP); // sinks output node
        const double iSum = iN - iP;
        const double gb = 1.0 / (1.0 + s.beta);

        // Driver base: the drive is coupled in DC-free (interstage coupling),
        // so the source is referenced at the divider's Thevenin voltage: it
        // sets the idle point with rs carrying no DC current, while keeping
        // the rs source impedance at signal frequencies.
        F[0] = (vb - vin - s.vth) / s.rs + (vb - s.vcc) / s.rb1 + vb / s.rb2
             + (vb + s.nfbRef - vo) / s.rf + op.ib;
        // Driver emitter: degeneration to ground carries the emitter current
        // (ic + ib). The global feedback returns to the BASE node (see the
        // rf note above), not here.
        F[1] = ve / s.reD - (op.ic + op.ib);
        // Driver collector: load from the supply, collector current, and the
        // pair's base current drawn through the spreader.
        F[2] = (vc - s.vcc) / s.rcD + op.ic + iSum * gb;

        // Collector saturation floor. A real BJT's collector cannot sink
        // below its emitter (Vce bottoms at Vce_sat ~ 0.2 V). The junction
        // limiter's 0.08-slope tail suppresses exactly that conduction,
        // which admits nonphysical roots in deep saturation where the
        // collector sits BELOW the emitter and then tracks the base upward
        // as drive grows -- the transfer-curve fold-back that reversed one
        // half of the waveform (the double-dip "W"). This term re-clamps
        // the collector smoothly. C1 everywhere (soft-abs), Jacobian
        // consistent.
        const double vceSat = 0.25;
        const double over   = (ve + vceSat) - vc;   // > 0 below the floor
        const double w      = 0.03;                 // soft-knee width [V]
        const double root   = std::sqrt (over * over + w * w);
        const double sSat   = 0.5 * (over + root);  // smooth max(0, over)
        const double dsd    = 0.5 * (1.0 + over / root);
        constexpr double kSat = 0.08;               // clamp conductance [S]
        F[2] -= kSat * sSat;
        // Output node: device current must feed load + feedback.
        F[3] = -iSum + vo / s.rl + (vo - s.nfbRef - vb) / s.rf;

        if (J == nullptr)
            return;

        // Driver derivative shorthand (w.r.t. vbe = vb-ve, vbc = vb-vc).
        const double ibB = op.dib_dvbe, ibC = op.dib_dvbc;
        const double icB = op.dic_dvbe, icC = op.dic_dvbc;
        // Pair transconductance: diSum/dvc = g, diSum/dvo = -g (degenerated
        // junction slopes; both junctions share the differential drive uN).
        const double g = diN + diP;

        auto& j = *J;
        for (auto& row : j) row.fill (0.0);

        j[0][0] = 1.0 / s.rs + 1.0 / s.rb1 + 1.0 / s.rb2 + 1.0 / s.rf + ibB + ibC;
        j[0][1] = -ibB;
        j[0][2] = -ibC;
        j[0][3] = -1.0 / s.rf;
        j[1][0] = -(icB + icC) - (ibB + ibC);
        j[1][1] = 1.0 / s.reD + icB + ibB;
        j[1][2] = icC + ibC;
        j[2][0] = icB + icC;
        j[2][1] = -icB - kSat * dsd;
        j[2][2] = 1.0 / s.rcD - icC + g * gb + kSat * dsd;
        j[2][3] = -g * gb;
        j[3][0] = -1.0 / s.rf;
        j[3][2] = -g;
        j[3][3] = g + 1.0 / s.rl + 1.0 / s.rf;
    }

    // Newton solve of the stage at input voltage `vin`, warm-seeded.
    // Continuation from the previous sample's state, with a retry from the
    // quiescent seed when it does not converge (preferring a *converged*
    // attempt over one that merely has a smaller residual).
    PpState solve (double vin, Vec& seed) const
    {
        auto evaluateFn = [&] (const Vec& x, Vec& F, Mat& J)
        { evaluate (*this, vin, x, F, &J); };
        auto residualOnly = [&] (const Vec& x, Vec& F)
        { evaluate (*this, vin, x, F, nullptr); };

        auto firstAttempt = seed;
        auto r1 = even::NewtonSolver<4>::solveCombined (evaluateFn, residualOnly, firstAttempt);

        if (! r1.converged)
        {
            auto retry = quiescentSeed;
            auto r2 = even::NewtonSolver<4>::solveCombined (evaluateFn, residualOnly, retry, 64);
            if (r2.converged)
            {
                firstAttempt = retry;
                r1 = r2;
            }
            else if (r2.residualNorm < r1.residualNorm)
            {
                firstAttempt = retry;
                r1 = r2;
            }
        }

        seed = firstAttempt;
        // Physical range guards: the driver and output nodes have no path
        // outside the supply-referenced range in any real root (the output
        // node is fed by junction current sources into rl/rf only).
        for (int i = 0; i < 4; ++i)
            seed[(size_t) i] = std::clamp (seed[(size_t) i], -20.0, vcc + 1.0);
        return { seed[0], seed[1], seed[2], seed[3] };
    }

private:
    // One degenerated pair junction: solve
    //   i - IsP*(ex((vLim(vArg) - i*reP)/Vt) - 1) = 0
    // for the junction current i. Strictly monotone in i (slope 1 + reP*gm
    // >= 1) => unique root, so ANY converged result is THE root regardless
    // of seed -- warm starting changes only the iteration count, never the
    // answer.
    //
    // Warm start: the root's slope di/dvArg is smooth in vArg, so a linear
    // extrapolation from the cache's previous (vArg, i) pair lands within a
    // fraction of the degeneration width of the new root and the Newton hits
    // its quadratic phase immediately. |dV| beyond 4 V (region switch)
    // falls back to the physical cold seed.
    //
    // Deep reverse bias: x < -40 puts ex(x) below 4e-18 (~1e-32 A through
    // IsP), indistinguishable from 0 at the 1e-10 solver tolerance, so the
    // exponential (and its Newton iterations) are skipped entirely -- the
    // OFF junction of the pair sits there nearly every sample.
    static double juncSolve (const Ba283OutputStage& s,
                             double& cacheV, double& cacheI, double& cacheS,
                             double vArg, double& di_dvArg)
    {
        const double v    = even::BjtModel::lim (vArg);
        const double limd = even::BjtModel::limd (vArg);

        double i;
        const double dV = vArg - cacheV;
        if (dV == dV && std::abs (dV) < 4.0) // NaN compare: cold cache
            i = cacheI + cacheS * dV;
        else
            i = s.IsP * (std::exp (std::min (v / s.Vt, 30.0)) - 1.0);

        for (int it = 0; it < 24; ++it)
        {
            const double x = std::min ((v - i * s.reP) / s.Vt, 30.0);
            if (x < -40.0) { i = -s.IsP; break; } // deep reverse bias: e ~ 0
            double e, d;
            even::BjtModel::exPair (x, e, d);
            const double f    = s.IsP * (e - 1.0);  // target current
            const double gm   = s.IsP / s.Vt * d;   // d(target)/dvj
            const double df   = 1.0 + gm * s.reP;   // d(i - f)/di
            const double step = (i - f) / df;
            i -= step;
            if (std::abs (step) < 1.0e-13)
                break;
        }
        const double x = std::min ((v - i * s.reP) / s.Vt, 30.0);
        double e = 0.0, gm = 0.0;
        if (x >= -40.0)
        {
            double d;
            even::BjtModel::exPair (x, e, d);
            gm = s.IsP / s.Vt * d;
        }
        di_dvArg = gm * limd / (1.0 + gm * s.reP);
        cacheV = vArg;
        cacheI = i;
        cacheS = di_dvArg;
        return s.IsP * (e - 1.0);
    }
};

} // namespace even
